### PR TITLE
Fix xcode 12 builds

### PR DESCRIPTION
**Pull request by filipef101**
This upgrades to latest sdk and allows to build in latest xcode

### CODE REVIEW

**Comment by filipef101** [comment]
@Gustash Can you review?

**Comment by filipef101** [comment]
I think it makes sense to do a major version bump after this as afaik it will only work with XCode 12.1.X
Right now it only works with XCode 11.4

**Comment by filipef101** [comment]
Alternatively, you can drop the dependency on giphy. And then the users should add the necessary dependency they need for their xcode version. 
(note one of the commits is needed for giphy 2.x.x)

**Review by Gustash — APPROVED** [review]

**Comment by Gustash** [comment]
Thanks @filipef101! Sorry,  I only had time to get to this now. I'll do a major version bump, I think most users actively deploying to the App Store need to be on Xcode 12 now anyway, so no worries on breaking older versions 😊

**Pull request merged**
