### PR TITLE
Update GiphyModule.kt

### PR DESCRIPTION
**Pull request by bharmalhusen**
1. Kotlin error in Android
2. Added Rating support
3. Might fix this issue https://github.com/Gustash/react-native-giphy-keyboard/issues/14

### CODE REVIEW

**Comment by krunalbad** [comment]
Awesome work @bharamalhusen . This might fix my issue.... Let me try running your fork .... This should definitely be merged

**Review by reyalpsirc — APPROVED** [review]
Seems good to me

**Review by filipef101 — APPROVED** [review]

**Comment by filipef101** [comment]
@Gustash Can we merge this?

**Comment by Gustash** [comment]
This package has now been deprecated in favor of the official `@giphy/react-native-sdk` library.

**Pull request closed without merging**
